<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sharepoint_formhandler"
 *
 * Auto generated by Extension Builder 2013-01-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Sharepoint Formhandler',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Julian Kleinhans, Erik Frister',
	'author_email' => 'julian.kleinhans@aijko.de, ef@aijko.de',
	'author_company' => 'aijko GmbH, aijko GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'formhandler' => '',
			'sharepoint_connector' => '',
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>